### ISSUE TITLE
Theme the sidebar, tree and title bar.

### ISSUE THREAD

**Issue by ehellman** [gluons/vscode-ramda-theme#2]
Hi there!

Are you planning on theming the rest of the application as well? This was my favorite syntax scheme in Atom, but it's difficult to use in VS Code when it looks so wonky without the rest of the application following the same color scheme.

Great job with the rest!

**Comment by gluons** [comment]
> Are you planning on theming the rest of the application as well?

No.  
I like Ramda REPL color and I use VSCode as my primary IDE. So, I made this.

---

> This was my favorite syntax scheme in Atom

Did you mean [juliancoleman/ramda-syntax](https://github.com/juliancoleman/ramda-syntax)?  
That theme is my the most favorite theme on @atom too.  
After I moved to VSCode. I can't find any theme like that. So, I made this.

---

> it's difficult to use in VS Code when it looks so wonky without the rest of the application following the same color scheme

Agree. Ramda doesn't provide any official color scheme.  
So I try to get this theme looked like their REPL as much as possible.  

I've explored [REPL](https://github.com/ramda/repl). They use [`dracula` theme of CodeMirror](https://codemirror.net/demo/theme.html#dracula). 
 
**But [CodeMirror](https://codemirror.net/)'s `dracula` doesn't look exactly like [Dracula theme](https://draculatheme.com/).  
It's really different.**
