### ISSUE TITLE
Support react short syntax

### ISSUE THREAD

**Issue by explooosion** [gluons/vscode-ramda-theme#4]
Hi @gluons !

I really love this theme style.

Hope to support [react short syntax](https://ru.react.js.org/docs/fragments.html#short-syntax).

![image](https://user-images.githubusercontent.com/13682994/83712801-26b64100-a659-11ea-8d8d-0f1683eb11f0.png)

Thank you.

**Comment by explooosion** [comment]
@gluons Hi 

I found that I can choose `TypeScriptReact` to solve this problem.
![image](https://user-images.githubusercontent.com/13682994/83714696-16549500-a65e-11ea-9008-c8053ca55f7f.png)

Maybe you don’t need to update. 
You can decide whether to close this issue.  😊


ref: https://github.com/Microsoft/vscode/issues/62253

**Comment by explooosion** [comment]
My extensions [Babel ES6/ES7](https://marketplace.visualstudio.com/items?itemName=dzannotti.vscode-babel-coloring) is in conflict, thank you for your response. 😅

**Comment by gluons** [comment]
Oh! OK thank you. 😊
